#!/usr/bin/env sh

set -euo pipefail

TARGET_HOST="${TARGET_HOST:-localhost}"

while true
do
    if [ "$(($RANDOM % 3))" == "0" ]; then
        curl -s "http://${TARGET_HOST}:62086/random-error" > /dev/null
    fi
    if [ "$(($RANDOM % 4))" == "0" ]; then
        curl -s "http://${TARGET_HOST}:62086/" > /dev/null
    fi
    sleep 0.05
done
