version: "3.9"

networks:
  prom:

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    expose:
      - 9100

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - ./examples/otel/configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./examples/otel/configs/slack_url.txt:/etc/alertmanager/slack_url
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    expose:
      - 9093
    ports:
      - "9093:9093"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./examples/otel/configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./examples/otel/configs/autometrics.rules.yml:/etc/prometheus/autometrics.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    expose:
      - 9090
    ports:
      - "9090:9090"
    depends_on:
      - alertmanager
      - node-exporter
      - web-server

  web-server:
    build:
      context: .
      dockerfile: examples/otel/Dockerfile
    environment:
      AUTOMETRICS_SERVICE_NAME: autometrics_otel
      AUTOMETRICS_OTLP_URL: $AUTOMETRICS_OTLP_URL
    container_name: web-server-otel
    restart: unless-stopped
    expose:
      - 62086
    ports:
      - "62086:62086"

  load-server:
    build:
      context: .
      dockerfile: examples/otel/load.Dockerfile
    environment:
      TARGET_HOST: web-server-otel
    container_name: load-server-otel
    restart: unless-stopped
    depends_on:
      - web-server
