global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "web-server"
    static_configs:
    - targets: ["web-server:62086"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]
