#!/bin/sh

set -euo pipefail

VERSION=${VERSION:-development}
COMMIT=`git log -1 --format="%H"`
BUILD_TIME=`date -Iseconds`
SCRIPT_DIR="$( dirname -- "$( readlink -f -- "$0"; )"; )"


go build -v -ldflags="-X 'main.Version=${VERSION}' -X 'main.Commit=${COMMIT}' -X 'main.BuildTime=${BUILD_TIME}'" -o web-server ${SCRIPT_DIR}/../cmd/main.go
