#!/usr/bin/env bash

set -euo pipefail

BUILD_PACK="github.com/autometrics-dev/autometrics-go/internal/build"
VERSION=`git describe --tags`
USER=`id -u -n`
DATE=`date -u`
SCRIPT_DIR="$( dirname -- "$( readlink -f -- "$0"; )"; )"

echo "Building version ${VERSION} (${USER} @ ${DATE})"

go build -v -a -ldflags="-X '${BUILD_PACK}.Version=${VERSION}' -X '${BUILD_PACK}.User=${USER}' -X '${BUILD_PACK}.Time=${DATE}'" ${SCRIPT_DIR}/../cmd/autometrics/main.go
