name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Check Format
        run: |
          bad_files="$(gofmt -s -l .)"
          if [[ -n $bad_files ]]; then
              printf -- "Some files are not formatted: %s\n" "$bad_files"
              exit 1
          fi

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
