name: "Go Coverage"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 10

    - uses: gwatts/go-coverage-action@v1
      continue-on-error: true
      with:
        cover-pkg: ./...
